# Generated by Django 5.2.17 on 2026-10-04 17:20

import apps.attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('object_id', models.UUIDField()),
                ('kind', models.CharField(blank=True, db_index=True, default='', help_text='Clasificación definida por el producto (contrato, factura, receta...).', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to=apps.attachments.models.attachment_upload_path, validators=[apps.attachments.models.UploadValidator()])),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=100)),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('sha256', models.CharField(db_index=True, editable=False, help_text='Huella del contenido para comprobar que el archivo no fue alterado.', max_length=64)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx')],
            },
        ),
    ]
