# Generated by Django 5.2.17 on 2026-10-08 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kernel', '0002_securityevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='groups',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='permission',
            field=models.ForeignKey(blank=True, help_text='Leave empty to show the item to every signed-in user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='auth.permission'),
        ),
    ]
