"""
Download the third-party front-end assets into kernel/static/vendor so the
app works without internet access (on-premise installs, local Wi-Fi only).

Run from the project root after changing a version or the icon list:

    python scripts/update_vendor.py

Only minified builds are downloaded. The Material Symbols font is a subset
holding just ICON_NAMES: an icon missing from the list renders as its plain
name, so add it here and run the script again.
"""
import re
import urllib.request
from pathlib import Path

VENDOR_DIR = Path(__file__).resolve().parent.parent / 'kernel' / 'static' / 'vendor'

BOOTSTRAP = '5.3.8'
HTMX = '2.0.11'
ALPINE = '3.17.4'

FILES = {
    'bootstrap/bootstrap.min.css': f'https://cdn.jsdelivr.net/npm/bootstrap@{BOOTSTRAP}/dist/css/bootstrap.min.css',
    'bootstrap/bootstrap.bundle.min.js': f'https://cdn.jsdelivr.net/npm/bootstrap@{BOOTSTRAP}/dist/js/bootstrap.bundle.min.js',
    'htmx/htmx.min.js': f'https://cdn.jsdelivr.net/npm/htmx.org@{HTMX}/dist/htmx.min.js',
    'alpinejs/alpine.min.js': f'https://cdn.jsdelivr.net/npm/alpinejs@{ALPINE}/dist/cdn.min.js',
}

# Common icons for business apps (navigation, CRUD, inventory, documents).
# Names: https://fonts.google.com/icons
ICON_NAMES = [
    # Navigation and layout
    'apps', 'arrow_back', 'arrow_downward', 'arrow_forward', 'arrow_upward',
    'chevron_left', 'chevron_right', 'close', 'dashboard', 'expand_less',
    'expand_more', 'home', 'menu', 'more_horiz', 'more_vert', 'open_in_new',
    # Actions
    'add', 'add_circle', 'block', 'check', 'content_copy', 'delete', 'done_all',
    'download', 'edit', 'filter_alt', 'filter_list', 'print', 'redo', 'refresh',
    'remove', 'save', 'search', 'sort', 'swap_horiz', 'sync', 'undo', 'upload',
    'visibility', 'visibility_off',
    # Status and feedback
    'cancel', 'check_circle', 'cloud_off', 'error', 'help', 'info',
    'notifications', 'pending', 'schedule', 'warning',
    # People and access
    'account_circle', 'admin_panel_settings', 'badge', 'group', 'key', 'lock',
    'login', 'logout', 'person', 'person_add', 'settings',
    # Contact and places
    'call', 'location_on', 'mail', 'store',
    # Documents and records
    'attach_file', 'backup', 'calendar_month', 'description', 'folder',
    'history', 'picture_as_pdf', 'receipt_long', 'restore', 'table_view',
    # Inventory, sales and money
    'barcode_scanner', 'category', 'factory', 'inventory', 'inventory_2',
    'label', 'local_shipping', 'medication', 'payments', 'point_of_sale',
    'qr_code_scanner', 'shopping_cart', 'warehouse',
    # Reports
    'bar_chart', 'trending_down', 'trending_up',
]

# Fixed weight/size/grade keep the subset small; FILL stays variable so an
# icon can switch to its filled version (e.g. the active menu entry).
ICONS_CSS_URL = (
    'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined'
    ':opsz,wght,FILL,GRAD@24,400,0..1,0'
    '&icon_names={names}&display=block'
)

# Google serves woff2 only to browsers it recognizes.
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'

ICONS_CSS = """\
/* Material Symbols Outlined, subset generated by scripts/update_vendor.py */
@font-face {
  font-family: 'Material Symbols Outlined';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url(material-symbols-outlined.woff2) format('woff2');
}

.icon {
  font-family: 'Material Symbols Outlined';
  font-weight: normal;
  font-style: normal;
  font-size: 1.25em;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  vertical-align: -0.225em;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
  user-select: none;
}

.icon-filled {
  font-variation-settings: 'FILL' 1;
}
"""


def fetch(url):
    request = urllib.request.Request(url, headers={'User-Agent': USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def strip_source_map(content):
    """Drop the source map reference: the .map files are not vendored, and
    collectstatic with manifest storage fails on references to missing files."""
    return re.sub(rb'\n?/[/*][#@] sourceMappingURL=\S+( \*/)?\s*$', b'\n', content)


def save(relative_path, content):
    path = VENDOR_DIR / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    print(f'{relative_path:45} {len(content) / 1024:8.1f} KB')


def main():
    for relative_path, url in FILES.items():
        save(relative_path, strip_source_map(fetch(url)))

    # Google requires the icon names in alphabetical order.
    names = ','.join(sorted(set(ICON_NAMES)))
    css = fetch(ICONS_CSS_URL.format(names=names)).decode()
    font_url = re.search(r'src: url\((.+?)\) format', css).group(1)
    save('material-symbols/material-symbols-outlined.woff2', fetch(font_url))
    save('material-symbols/material-symbols.css', ICONS_CSS.encode())


if __name__ == '__main__':
    main()
